CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=70
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=70

CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y
CONFIG_BT_MAX_PAIRED=4
CONFIG_ZMK_LED_INDICATOR=n
CONFIG_LED=n
# 删除 ZMK_BLE_AUTO_START_ADVERTISING，新版本不再支持该选项
