# 开启GPIO矩阵扫描驱动
CONFIG_ZMK_KSCAN_GPIO_DRIVER=y

# 消抖
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=15
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=15

# 蓝牙、USB基础
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y

# 蓝牙配对保存设备数量（新版名字）
CONFIG_BT_MAX_PAIRED=4

# 上电自动广播蓝牙
CONFIG_ZMK_BLE_AUTO_START_ADVERTISING=y
