CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=15
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=15
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_USB_AUTO_DETECT=y
CONFIG_ZMK_BLE_AUTO_ADVERTISE_ON_START=y
CONFIG_ZMK_BLE_BOND_MAX=4
